---
- name: Restore configure_time.yml
  hosts: all
  gather_facts: no
  tasks:
    - name: Set timezone Asia/Seoul
      timezone:
        name: 'Asia/Seoul'

    - name: Restart the NTP service
      service:
        name: chronyd
        state: restarted