---
- name: Restore playbook.yml
  hosts: all
  tasks:
    - name: Remote package - httpd
      yum:
        name: httpd
        state: absent

    - name: Remove the file - /var/www/html/index.html
      file: 
        path: /var/www/html/index.html
        state: absent

    - name: Close the port/service on firewalld
      firewalld:
        service: "{{ item }}"
        state: disabled
        permanent: yes
        immediate: yes
      loop: 
        - http
        - https
